// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXlScGZSH5XPDBk8iLdVu4gC9UJnKCOe4',
    appId: '1:608075934960:web:2a26d81f91d2db63016635',
    messagingSenderId: '608075934960',
    projectId: 'mycashbook-3ec5a',
    authDomain: 'mycashbook-3ec5a.firebaseapp.com',
    storageBucket: 'mycashbook-3ec5a.firebasestorage.app',
    measurementId: 'G-SC31HTJ2SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr65qNERUYSa-67X27fWXaCi_r_h346A8',
    appId: '1:608075934960:android:9e6cbbf8717fe1ad016635',
    messagingSenderId: '608075934960',
    projectId: 'mycashbook-3ec5a',
    storageBucket: 'mycashbook-3ec5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe-Wcp7yu3LfSSwvN--OOo6wrIwdVuCHg',
    appId: '1:608075934960:ios:5a79880813425560016635',
    messagingSenderId: '608075934960',
    projectId: 'mycashbook-3ec5a',
    storageBucket: 'mycashbook-3ec5a.firebasestorage.app',
    iosBundleId: 'com.example.myCashbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe-Wcp7yu3LfSSwvN--OOo6wrIwdVuCHg',
    appId: '1:608075934960:ios:5a79880813425560016635',
    messagingSenderId: '608075934960',
    projectId: 'mycashbook-3ec5a',
    storageBucket: 'mycashbook-3ec5a.firebasestorage.app',
    iosBundleId: 'com.example.myCashbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXlScGZSH5XPDBk8iLdVu4gC9UJnKCOe4',
    appId: '1:608075934960:web:75b49cfcd9df7025016635',
    messagingSenderId: '608075934960',
    projectId: 'mycashbook-3ec5a',
    authDomain: 'mycashbook-3ec5a.firebaseapp.com',
    storageBucket: 'mycashbook-3ec5a.firebasestorage.app',
    measurementId: 'G-LBT33TB62K',
  );
}
